export const ALBUM_LIST_REQUEST = 'ALBUM_LIST_REQUEST';
export const ALBUM_LIST_SUCCESS = 'ALBUM_LIST_SUCCESS';
export const ALBUM_LIST_FAILURE = 'ALBUM_LIST_FAILURE';

export const ABLUM_DETAIL_REQUEST = 'ABLUM_DETAIL_REQUEST';
export const ALBUM_DETAIL_SUCCESS = 'ALBUM_DETAIL_SUCCESS';
export const ALBUM_DETAIL_FAILURE = 'ALBUM_DETAIL_FAILURE';

export const ARTIST_LIST_REQUEST = 'ARTIST_LIST_REQUEST';
export const ARTIST_LIST_SUCCESS = 'ARTIST_LIST_SUCCESS';
export const ARTIST_LIST_FAILURE = 'ARTIST_LIST_FAILURE';
